config/routes.rb
Rails.application.routes.draw do
  get 'todotasks/destroyall', to:"todotasks#destroyall"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todotasks#index"
  resources :todotasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todotask.rb
class Todotask < ApplicationRecord
    validates :task, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todotasks_controller.rb
class TodotasksController < ApplicationController
  def index
    @todotask = Todotask.all
    @len = @todotask.length
  end
  def new
    @todotask = Todotask.new
  end
  def create 
    @todotask = Todotask.new(valid_params)

    if @todotask.save
      redirect_to todotasks_url
    else
      render :new, status: 502
    end
  end

  def destroy
    @todotask = Todotask.find(params[:id])
    @todotask.destroy
    redirect_to todotasks_url
  end

  def edit
    @todotask = Todotask.find(params[:id])
  end

  def update
    @todotask = Todotask.find(params[:id])

    if @todotask.update(valid_params)
      redirect_to todotasks_url
    else
      render :new, status: 502
    end
  end

  def destroyall
    if Todotask.connection.execute("DELETE FROM todotasks")
      @todotask = Todotask.all
      @len = @todotask.length
    end
    render :index
  end

  private
  def valid_params
    params.require(:todotask).permit(:task, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todotasks_helper.rb
module TodotasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todotasks/edit.html.erb
<div class="box">
<%= form_with model: @todotask do |form| %>
    <div>
        <%= form.label :task%>
        <%= form.text_field :task%>
        <% @todotask.errors.full_messages_for(:task).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status%>
        <%= form.select :status, ["pending", "progress", "completed"]%>
    </div>

    <div>
        <%= form.submit "Update task"%>
    </div>
    
<% end %>
</div>

app/views/todotasks/index.html.erb
<div class="box">
<div>
<h1> TODO </h1>

<% if @len == 0%>
    <h3> No tasks </h3>
<%end%>

<table class="table table-striped" cellspacing="20px" >
  <tr>
    <th>S.No</th>
    <th>Task</th>
    <th>Status</th>
    <th></th>
    <th></th>
  </tr>
  <%task_counter = 0%>
    <% @todotask.each do |task| %>
    <tr>
        <%task_counter = task_counter + 1%>
        <td> <%= task_counter %> </td>
        <td> <%= task.task %> </td>
        <td> <%= task.status %> </td>
        <td> <%= link_to "Edit", edit_todotask_path(task) %> </td>
        <td> <%= link_to "Delete", todotask_path(task), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
        </td>
  </p>
    </tr>
    <% end %>
  
</table>
<div style="display: flex; justify-content: space-between">
<button type="button" class="btn btn-primary" onclick="window.location.href='<%= new_todotask_path%>'">Add task</button>
<button type="button" class="btn btn-primary" onclick="window.location.href='<%= todotasks_destroyall_path%>'">Delete all</button>
</div>
<div>

</div>

app/views/todotasks/new.html.erb
<div class="box">
<%= form_with model: @todotask do |form| %>
    <div>
        <%= form.label :task%>
        <%= form.text_field :task%>
        <% @todotask.errors.full_messages_for(:task).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.label :status%>
        <%= form.select :status, ["pending", "progress", "completed"], selected: "progress"%>
    </div>

    <div>
        <%= form.submit "Add task"%>
    </div>
    
<% end %>
</div>